let index=-1,answers=[],autoNext=true,advanceTimer=null;
const app=document.getElementById('app'),total=questions.length;
function cancelAdvance(){clearTimeout(advanceTimer);advanceTimer=null;}
function focusTitle(){requestAnimationFrame(()=>{app.querySelector('h1')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});});}
function start(){cancelAdvance();index=0;answers=[];render();focusTitle();}
function calculate(input){
 if(!Array.isArray(input)||input.length!==total||!input.every(a=>Number.isInteger(a)&&a>=0&&a<4))throw new Error(`需要${total}个0至3之间的整数答案`);
 const sums=dimensions.map(()=>0),counts=dimensions.map(()=>0);input.forEach((a,i)=>{sums[questions[i].dim]+=questions[i].options[a].value;counts[questions[i].dim]++;});const vector=sums.map((n,i)=>n/counts[i]);
 const ranked=animals.map((animal,id)=>({animal,id,d:Math.sqrt(animal.v.reduce((s,v,j)=>s+(v-vector[j])**2,0)/dimensions.length)})).sort((a,b)=>a.d-b.d||a.id-b.id);
 return{animal:ranked[0].animal,second:ranked[1].animal,ranked,vector,close:ranked[1].d-ranked[0].d<.15,balanced:vector.every(v=>Math.abs(v)<=.5)};
}
function describeDimension(d,v){return Math.abs(v)<.5?`你在「${d.name}」上没有明显偏向，更可能随情境在两种方式之间切换。`:v<0?d.low:d.high;}
function choose(a,allowAuto=true){if(index<0||index>=total)return;cancelAdvance();answers[index]=a;render();app.querySelectorAll('.option')[a]?.focus();if(autoNext&&allowAuto&&index<total-1){const chosenIndex=index;advanceTimer=setTimeout(()=>{if(index===chosenIndex)next();},650);}}
function next(){cancelAdvance();if(index<0||index>=total||answers[index]===undefined)return;index++;render();focusTitle();}
function previous(){cancelAdvance();if(index>0){index--;render();focusTitle();}}
function render(){clearPoster();if(index<0){app.innerHTML=`<section class="intro"><div><div class="eyebrow">给自己一份温柔的使用说明书</div><h1 tabindex="-1">你的心里，<br>住着哪只<em>小动物？</em></h1><p class="description">在人群里、在关系里、在一个人待着的时候，你会露出哪一面？从日常的小选择里，认领自己的内心小动物。</p><div class="meta"><span>${total} 道情境题</span><span>约 4–6 分钟</span><span>6 个维度</span></div><button class="primary" id="start">遇见我的小动物 ↗</button><small>按最近一个月的自己选择。没有标准答案，也不用选“应该成为”的样子。</small></div><div class="art"><img src="animals.png" alt="六只小动物相聚在蓝色花园"><div class="art-note"><span>每一种你，都有自己的可爱。</span><span>✦</span></div></div></section><section class="intro-details"><h2>认识自己的六个侧面</h2><div class="dimension-list">${dimensions.map(d=>`<div><strong>${d.name}</strong><span>${d.left} / ${d.right}</span></div>`).join('')}</div><p>你会得到：小动物结果、六维偏好地图、与你的回答对应的解释，以及一张可保存的专属海报。</p></section>`;document.getElementById('start').onclick=start;return;}
 if(index>=total){renderResult();return;}const q=questions[index],d=dimensions[q.dim];app.innerHTML=`<section class="quiz"><div class="progress-label"><span>${d.name} · ${Math.floor(index/4)+1} / 6</span><span>${index+1} / ${total}</span></div><div class="track" role="progressbar" aria-label="已完成题目" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${answers.filter(a=>a!==undefined).length}"><div class="fill" style="width:${answers.filter(a=>a!==undefined).length/total*100}%"></div></div><h1 tabindex="-1" id="question">${q.text}</h1><p class="hint">选最近一个月更常见的反应，不必追求每次都符合。</p><div class="options" role="radiogroup" aria-labelledby="question">${q.options.map((o,a)=>`<button class="option" role="radio" aria-checked="${answers[index]===a}" data-choice="${a}"><span class="letter">${'ABCD'[a]}</span><span>${o.text}</span></button>`).join('')}</div><label class="auto-setting"><input id="auto-next" type="checkbox" ${autoNext?'checked':''}> 选择后自动进入下一题</label><p class="auto-note">${index===total-1?'最后一题由你确认，再生成结果。':'可返回修改；使用方向键选择时，由你确认下一题。'}</p><div class="controls"><button class="text-button" id="prev" ${index===0?'disabled':''}>← 上一题</button><button class="primary" id="next" ${answers[index]===undefined?'disabled':''}>${index===total-1?'生成我的结果 ✦':'下一题 →'}</button></div></section>`;
 app.querySelectorAll('[data-choice]').forEach(b=>{b.onclick=()=>choose(Number(b.dataset.choice));b.onkeydown=e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();choose((Number(b.dataset.choice)+(['ArrowDown','ArrowRight'].includes(e.key)?1:3))%4,false);}}});document.getElementById('prev').onclick=previous;document.getElementById('next').onclick=next;document.getElementById('auto-next').onchange=e=>{cancelAdvance();autoNext=e.target.checked;};
}
function renderResult(){const r=calculate(answers),a=r.animal,id=animals.indexOf(a),topDims=r.vector.map((v,j)=>({v,j})).sort((x,y)=>Math.abs(y.v)-Math.abs(x.v)||x.j-y.j).slice(0,3);
 const evidence=topDims.map(({j,v})=>{const item=questions.map((q,i)=>({q,i,value:q.options[answers[i]].value})).filter(o=>o.q.dim===j).sort((x,y)=>Math.abs(x.value-v)-Math.abs(y.value-v))[0];return `<div class="evidence"><h3>${dimensions[j].name} · ${Math.abs(v)<.5?'灵活切换':v<0?dimensions[j].left:dimensions[j].right}</h3><p>${describeDimension(dimensions[j],v)}</p><small>例如，第 ${item.i+1} 题你选了：“${item.q.options[answers[item.i]].text}”。</small></div>`;}).join('');
 const alternatives=r.ranked.slice(1,3).map((entry,k)=>{const nearest=dimensions.map((d,j)=>({d,gap:Math.abs(entry.animal.v[j]-r.vector[j])})).sort((x,y)=>x.gap-y.gap)[0];return `<article class="alternative"><span>接近的倾向 ${k+2}</span><h3>${entry.animal.emoji} ${entry.animal.name}</h3><p>在「${nearest.d.name}」上，你与这只小动物的设定较接近。</p><small>${entry.animal.tags.join(' · ')}</small></article>`;}).join('');
 app.innerHTML=`<section class="result"><div class="result-card"><div class="eyebrow">${r.balanced?'你有多面的小动物气质':r.close?'这次，你有两种接近的动物倾向':'本次回答更接近的小动物'}</div><div class="animal-emoji" aria-hidden="true">${a.emoji}</div><h1 tabindex="-1">${a.name}</h1><div class="tags">${a.tags.map(t=>`<span>${t}</span>`).join('')}</div><p>${a.line}</p></div><div class="result-grid"><article class="detail wide"><h2>为什么这次更像它？</h2><p>${r.balanced?'你的六个维度都比较居中，没有特别鲜明的单一倾向。下面展示距离最近的一种设定，值得结合另外两种一起看。':r.close?`你与「${a.name}」和「${r.second.name}」的距离很接近，可以把它们理解为同时存在的两种侧面。`:'这是综合六个维度后，与你本次回答距离最近的小动物设定。以下解释直接对应你的选择。'}</p>${evidence}</article><article class="detail wide"><h2>你的六维偏好地图</h2><div class="bars">${dimensions.map((d,j)=>`<div class="dimension-result"><div class="dimension-caption"><strong>${d.name}</strong><span>${Math.abs(r.vector[j])<.5?'两侧接近':r.vector[j]<0?'偏向'+d.left:'偏向'+d.right}</span></div><div class="bar-row"><span>${d.left}</span><div class="bar-track"><i class="bar-marker" style="left:${Math.max(3,Math.min(97,(r.vector[j]+2)/4*100))}%"></i></div><span style="text-align:right">${d.right}</span></div></div>`).join('')}</div><p class="note">每个维度由 4 道题等权计算。位置表示这次的偏好，不是能力高低、准确率或人群排名。</p></article><article class="detail wide"><h2>你也有它们的一面</h2><div class="alternatives">${alternatives}</div><p class="note">按与预设动物画像的距离排序；接近不代表你只能属于某一类。</p></article><article class="detail"><h2>♡ 相处时的一句说明</h2><p>${reminders[id][1]}</p><p class="note">可以试着用这句话表达需要，再按自己的习惯改一改。</p></article><article class="detail"><h2>☀ 适合尝试的充电方式</h2><p>${a.charge}</p></article><article class="detail wide"><h2>给这只小动物的温柔提醒</h2><p>${reminders[id][0]}</p><p class="note">这是这类动物设定的提醒，不一定适用于你的每一种关系。</p></article><article class="detail wide"><h2>今天的一件小事</h2><p>${a.task}</p></article></div><section class="poster-section" id="poster-region" aria-labelledby="poster-title"><h2 id="poster-title">把你的小动物，分享出去</h2><p id="poster-status" aria-live="polite">正在生成专属海报…</p><div class="poster-actions"><a class="primary" id="save-poster" hidden>保存海报</a><button class="secondary" id="share-poster" disabled>分享海报</button><button class="secondary" id="retry-poster" hidden>重新生成</button></div><img id="poster-image" class="poster-image" alt="${a.name}专属结果海报，可长按保存" hidden></section><details class="method detail"><summary>这份结果是怎样得到的？</summary><p>24 题分属六个维度。每题在本维度记为 −2、−1、1 或 2，各维度取 4 题平均值。再计算你与六种原创动物设定的均方根距离，距离越小越接近；完全同分时按固定顺序展示，并提示接近或多面倾向。</p><p>动物画像与阈值为创作设定，未经心理测量学验证。这是一份娱乐性的自我探索材料，不是诊断，也不应用来决定职业或关系。</p></details><div class="controls"><button class="secondary" id="restart">再测一次</button><button class="secondary" id="copy">复制结果文字</button></div><p class="status" aria-live="polite" id="status"></p></section>`;
 void mountAnimalPoster(a);document.getElementById('restart').onclick=()=>{cancelAdvance();index=-1;answers=[];render();focusTitle();};document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(`我的内心小动物是「${a.name}」${a.emoji}\n${a.line}\n${location.origin}${location.pathname}`);document.getElementById('status').textContent='已复制，可以粘贴给朋友。';}catch{document.getElementById('status').textContent='复制暂不可用，可以保存上方海报。';}};
}
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'complete_inner_animal_quiz',description:`提交全部${total}题并显示结果，替换当前答案。`,inputSchema:{type:'object',properties:{answers:{type:'array',items:{type:'integer',minimum:0,maximum:3},minItems:total,maxItems:total}},required:['answers'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const result=calculate(input?.answers);cancelAdvance();answers=[...input.answers];index=total;render();focusTitle();return{animal:result.animal.name,dimensions:result.vector};}})).catch(()=>{});}catch{}}
